#!/bin/sh

set -e

echo '+cargo test --all'
cargo test --all

echo '+cargo check --all'
cargo check --all

echo '+cargo clippy --all -- -D warnings'
cargo clippy --all -- -D warnings

echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check
