[package]
name = "rl-diablo-2-hack"
version = "0.1.0"
authors = ["riley"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
